markdown: kramdown
highlighter: rouge
#rdiscount:
#  extensions: [smart]
permalink: /posts/:categories/:title/
gems:
  - jekyll-sitemap
  - jekyll-mentions

name: Data Workshops
url: http://ucsdlib.github.io/workshops
description: A list of our workshops.
twitter: ucsdlibrary
datasvs: http://ucsd.libguides.com/data-services
rdcp: http://libraries.ucsd.edu/services/data-curation

# Enables/Disable future posts (posts with dates in the future) and drafts.  set using: True | False
future: True
